### ISSUE TITLE
Service Basic Usage and Responsibilities

### ISSUE THREAD

**Issue by clintberry** [ploio/ploio#3]
**ploioctl**

- Will send signals to initate "deployment tests" on ploio server (running on cluster that we are deploying to)
- Support for approving/denying of tests (when manual intervention is required)
- Support for cancelling tests (rollback)

**ploio-server**

- Will create necessary K8s YAML files from submitted ploio yaml and version and type of test
- Will either directly deploy new k8s yaml files (and/or routing instructions) or submit changes to a git repo that automatically deploys changes to the cluster
- Will watch for errors in deployment, or errors in the test and fail and rollback when it detects them
- Will manage state of all deployments and tests on the system

**ploio-github**

- Because an application in a github repo may be deployed to more than one k8s cluster, we can't put the github config/oauth-app in ploio-server. Also, configuring in ploioctl would require ploioctl to leave a running server to capture github events. So, I propose a separate service that can be run on any cluster, that exposes a URL for github to talk to, and a url for ploiod to talk to.

**Comment by derekperkins** [comment]
> submit changes to a git repo that automatically deploys changes to the cluster

I know you've brought this up before, but thinking about it as the next step in the pipeline is kind of awesome. Not only do you have your actual yaml changes and deployment history versioned outside the cluster, you now have the opportunity to kick off another CI process. Not exactly sure how I'd configure that yet, but it's very intriguing.

> Because an application in a github repo may be deployed to more than one k8s cluster, we can't put the github config/oauth-app in ploiod

I don't love the idea of having a separate service running to capture GitHub events. What about just having both ploio-servers register separately for notifications from GitHub?

**Comment by clintberry** [comment]
My concern with X number of ploio-servers all communicating with github is:

- It is a pain to add Oauth apps for each one
- Oauth apps don't quite behave the way I want anyway, so I am forced to use a GitHub app which acts as its own user
- You can't install multiple of the same github apps
- There is potential to make the github interface paid... I know I know...

**Comment by clintberry** [comment]
but that being said, we can build everything else to start and not worry about it :-)
